[toolchain]
package_manager = "npm"
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
aerospacer_protocol = "6qjCWo3diZmBwTHVn1CfegbNQxBMy1q2MqPHUEN5xja2"
aerospacer_oracle = "D8xkMuN8J1v7kH6R8Xd4RwMcTk1HETgfFN24sSB3ZoFJ"
aerospacer_fees = "h4ka5hAgZ5Ez7x4bjMiAqQHnuwnfry3aBiWNzUw3F7t"

[programs.devnet]
aerospacer_protocol = "6qjCWo3diZmBwTHVn1CfegbNQxBMy1q2MqPHUEN5xja2"
aerospacer_oracle = "D8xkMuN8J1v7kH6R8Xd4RwMcTk1HETgfFN24sSB3ZoFJ"
aerospacer_fees = "h4ka5hAgZ5Ez7x4bjMiAqQHnuwnfry3aBiWNzUw3F7t"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.ts'"
deploy_devnet = "anchor deploy --provider.cluster devnet"
deploy_mainnet = "anchor deploy --provider.cluster mainnet"
