[toolchain]
package_manager = "npm"
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
aerospacer_protocol = "eW6XmBQigY6bWkLmk153PncJdXTrHmgSoBzUaLS3GZe"
aerospacer_oracle = "2Vn1gNPEjVW4NbKrrBfNKtyYM6sLXiUkkPDVrCkT8cp9"
aerospacer_fees = "6j3Bpeu3HHKw63x42zjgV19ASyX8D29dB8rNGkPpypco"

[programs.devnet]
aerospacer_protocol = "eW6XmBQigY6bWkLmk153PncJdXTrHmgSoBzUaLS3GZe"
aerospacer_oracle = "2Vn1gNPEjVW4NbKrrBfNKtyYM6sLXiUkkPDVrCkT8cp9"
aerospacer_fees = "6j3Bpeu3HHKw63x42zjgV19ASyX8D29dB8rNGkPpypco"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.ts'"
test-oracle-devnet = "ANCHOR_PROVIDER_URL=https://api.devnet.solana.com npx ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/oracle-*.ts'"
test-fee-devnet = "ANCHOR_PROVIDER_URL=https://api.devnet.solana.com npx ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/fee-*.ts'"
deploy_devnet = "anchor deploy --provider.cluster devnet"
deploy_mainnet = "anchor deploy --provider.cluster mainnet"
init_oracle_devnet = "npx ts-node scripts/init-oracle-devnet.ts"
add_assets_devnet = "npx ts-node scripts/add-assets-devnet.ts"
test_prices_devnet = "npx ts-node scripts/test-prices-devnet.ts"
