[toolchain]
package_manager = "yarn"
anchor_version = "0.28.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
aerospacer_protocol = "mR3CUXYeYLjoxFJ1ieBfC9rLciZwe8feFYvXKdafihD"
aerospacer_oracle = "8gLDpdg9tFAtAnpZabd2w6V7qQikfqCKzPiNpx9Wcr3c"
aerospacer_fees = "8PC52W8S5WQ1X6gBBNQr5AvYYxVEa68DahEgFJAueZF4"
aerospacer_solana = "6kJZg8PDkutRui282AnspEnLcyExxcpsbCvyfBoTcDwN"

[programs.devnet]
aerospacer_protocol = "mR3CUXYeYLjoxFJ1ieBfC9rLciZwe8feFYvXKdafihD"
aerospacer_oracle = "8gLDpdg9tFAtAnpZabd2w6V7qQikfqCKzPiNpx9Wcr3c"
aerospacer_fees = "8PC52W8S5WQ1X6gBBNQr5AvYYxVEa68DahEgFJAueZF4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.ts'"
deploy_devnet = "anchor deploy --provider.cluster devnet"
deploy_mainnet = "anchor deploy --provider.cluster mainnet"
