[toolchain]
package_manager = "npm"
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
aerospacer_protocol = "9VW7X4D6SmjAMFYAUp7XASjpshW3QSk5QEf1cWdyjP24"
aerospacer_oracle = "5oqS8Q6eqMHGJUnKF4VrYE6JnjcFVRhgktrHErkyLoKx"
aerospacer_fees = "3nbhQ7bahEr733uiBYKmTgnuGFzCCnc6JDkpZDjXdomC"

[programs.devnet]
aerospacer_protocol = "9VW7X4D6SmjAMFYAUp7XASjpshW3QSk5QEf1cWdyjP24"
aerospacer_oracle = "5oqS8Q6eqMHGJUnKF4VrYE6JnjcFVRhgktrHErkyLoKx"
aerospacer_fees = "3nbhQ7bahEr733uiBYKmTgnuGFzCCnc6JDkpZDjXdomC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.ts'"
deploy_devnet = "anchor deploy --provider.cluster devnet"
deploy_mainnet = "anchor deploy --provider.cluster mainnet"
